---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r ECHO=TRUE}

data <-read.csv("activity.csv",na.strings = "NA",sep=",")
bad<- is.na(data$steps)

complete <- data[!bad,]
print(head(complete))
 
   
```


## What is mean total number of steps taken per day?
```{r ECHO=TRUE}
library(datasets)
x <- data.frame(Category=complete$date, 
                  Frequency=complete$steps)
  xSummary <- aggregate(x$Frequency, by=list(Category=x$Category), FUN=sum)

hist(xSummary$x,xlab="total number of steps taken each day",main="")
  
dev.off()

# Mean Number of steps:
mean(complete$steps)

# Median Number of Steps:
median(complete$steps)
```
## What is the average daily activity pattern?
```{r ECHO=TRUE}

day_act <-data.frame(Category=complete$interval, 
                  Frequency=complete$steps)
xAvg <- aggregate(day_act$Frequency, by=list(Category=day_act$Category), FUN=mean)


 plot(xAvg$Category,
       xAvg$x,        
       type="l",
       col="black", 
       xlab="5 minute interval", 
       ylab="Avg Steps", 
       main="Frequency of Steps per 5 minute interval")
  dev.off()
  


hold<- xAvg[which.max(xAvg$x), ]

#interval with max steps:
hold$Category
```
## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
